routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('survey.index');
});

Auth::routes([
    'register' => false,
    'reset' => false,
    'verify' => false,
]);

Route::group(['middleware' => 'auth'], function() {
    Route::resource('survey', 'SurveyController')
        ->only(['index', 'create', 'store']);
    
    Route::resource('export_request', 'ExportRequestController')
        ->only('index', 'create', 'store');
});

app/Models/ExportData.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Storage;

class ExportData extends Model
{
    protected $table = 'export_datas';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title', 'page',
        'export_request_id',
        'file_path',
    ];
    
    public function exportRequest() {
        return $this->belongsTo(ExportRequest::class);
    }
    
    public function getFileUrlAttribute()
    {
        return Storage::url($this->file_path);
    }
}

app/Models/ExportRequest.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Nicolaslopezj\Searchable\SearchableTrait;

class ExportRequest extends Model
{
    use SearchableTrait;
    
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'reference', 'from',
        'to', 'status'
    ];
    
    protected $casts = [
        'from' => 'datetime',
        'to' => 'datetime',
    ];
    
    const PENDING_STATUS = 'pending';
    const COMPLETE_STATUS = 'complete';
    const FAIL_STATUS = 'fail';
    
    /**
     * Searchable rules.
     *
     * @var array
     */
    protected $searchable = [
        /**
         * Columns and their priority in search results.
         * Columns with higher values are more important.
         * Columns with equal values have equal importance.
         *
         * @var array
         */
        'columns' => [
            'export_requests.reference' => 10,
            'export_requests.status' => 5,
        ]
    ];
    
    public function surveys() {
        return $this->belongsToMany(Survey::class);
    }
    
    public function export_data() {
        return $this->hasOne(ExportData::class);
    }
    
}

app/Http/Controllers/Api/ExportRequestController.php
<?php

namespace App\Http\Controllers\Api;

use App\Events\ExportRequestSubmitted;
use App\Http\Controllers\Controller;
use App\Http\Requests\Api\ExportRequest\StoreRequest;
use App\Models\ExportRequest;
use Illuminate\Http\Request;

class ExportRequestController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $q = $request->input('q');
    
        $export_requests = ExportRequest::with('export_data')
            ->withCount('surveys')
            ->latest('id')
            ->search($q)
            ->paginate(15);
        $export_requests->appends($request->except('page'));
    
        return api_response_data(true, $export_requests,
            flash_messages('Export requests list'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRequest $request)
    {
        $fromDate = $request->input('export_request.from');
        $toDate = $request->input('export_request.to');
        
        $exportRequest = new ExportRequest();
        $exportRequest->reference = uniqid('EXP');
        $exportRequest->from = $fromDate;
        $exportRequest->to = $toDate;
        $exportRequest->save();
        
        event(new ExportRequestSubmitted($exportRequest));
    
        return api_response_data(true, $exportRequest,
            flash_messages("Export requests created with success. Wait or make another GET request with parameter ?q={$exportRequest->reference} to check the status !"));
    }
    
}

app/Http/Controllers/ExportRequestController.php
<?php

namespace App\Http\Controllers;

use App\Events\ExportRequestSubmitted;
use App\Http\Requests\ExportRequest\StoreRequest;
use App\Models\ExportRequest;
use Carbon\Carbon;
use Illuminate\Http\Request;

class ExportRequestController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $q = $request->input('q');
    
        $export_requests = ExportRequest::with('export_data')
            ->withCount('surveys')
            ->latest('id')
            ->search($q)
            ->paginate(15);
        $export_requests->appends($request->except('page'));
    
        return view('export_request.index', compact('export_requests', 'q'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('export_request.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRequest $request)
    {
        $fromDate = $request->input('export_request.from');
        $toDate = $request->input('export_request.to');
        
        $exportRequest = new ExportRequest();
        $exportRequest->reference = uniqid('EXP');
        $exportRequest->from = $fromDate;
        $exportRequest->to = $toDate;
        $exportRequest->save();
        
        event(new ExportRequestSubmitted($exportRequest));
    
        $request->session()->flash('success', "Processing export request.
        Wait few minutes and reload the page or check the request status
        with reference <strong>{$exportRequest->reference}</strong>.");
        
        return redirect()->route('export_request.index');
    }
    
}

resources/views/export_request/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

        <div class="row justify-content-center">
            <div class="col-md-8">

                <p class="text-right">
                    {!! link_to(URL::previous(), 'Go back', ['class' => 'btn btn-md btn-info']) !!}
                </p>

                <div class="card">
                    <div class="card-header bg-info">
                        <div class="row justify-content-start">
                            <div class="col-md-6">
                                <h4>Create export request</h4>
                            </div>
                        </div>

                    </div>

                    <div class="card-body">
                        {!! Form::open(['route' => 'export_request.store', 'method' => 'post']) !!}
                            <div class="form-group">
                                {!! Form::label('export_request[from]', 'From') !!}
                                {!! Form::date('export_request[from]', now()->format('Y-m-d'), ['class' => 'form-control', 'required']) !!}
                            </div>
                            <div class="form-group">
                                {!! Form::label('export_request[to]', 'To') !!}
                                {!! Form::date('export_request[to]', now()->format('Y-m-d'), ['class' => 'form-control', 'required']) !!}
                            </div>
                            <div class="form-group">
                                {!! Form::submit('Save request', ['class' => 'btn btn-sm btn-info']) !!}
                            </div>
                        {!! Form::close() !!}
                    </div>

                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/export_request/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

        <div class="row justify-content-center">
            <div class="col-md-12">

                <p class="text-right">
                    {!! link_to_route('export_request.create', 'Create export request', null, ['class' => 'btn btn-md btn-info']) !!}
                </p>

                <div class="card">
                    <div class="card-header bg-info">
                        <div class="row justify-content-between">
                            <div class="col-md-3">
                                <h4>Export requests list</h4>
                            </div>

                            <div class="col-md-4">
                                <form class="form-inline pull-right">
                                    <input class="form-control mr-sm-2" type="search" value="{{$q}}" name="q" placeholder="Search reference." aria-label="Search">
                                    <button class="btn btn-outline-white my-sm-0 my-3" type="submit">Search</button>
                                </form>
                            </div>
                        </div>

                    </div>

                    <div class="card-body">

                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th scope="col">#</th>
                                        <th scope="col">Reference</th>
                                        <th scope="col">From</th>
                                        <th scope="col">To</th>
                                        <th scope="col">Status</th>
                                        <th scope="col">Surveys</th>
                                        <th class="text-center">Files</th>
                                    </tr>
                                </thead>
                                <tbody>
                                @forelse($export_requests as $export_request)
                                    <tr>
                                        <td>{{$export_request->id}}</td>
                                        <td>{{$export_request->reference}}</td>
                                        <td>{{$export_request->from->format('d/m/Y')}}</td>
                                        <td>{{$export_request->to->format('d/m/Y')}}</td>
                                        <td>{{$export_request->status}}</td>
                                        <td>{{$export_request->surveys_count}}</td>
                                        <td>
                                            @if($export_request->status == 'pending')
                                                Waiting...
                                            @else
                                                <div class="row">
                                                    <div class="col-md-6">
                                                        <a class="btn btn-sm btn-info mb-2" href="{{$export_request->export_data->file_url}}" download>
                                                            Download excel file
                                                        </a>
                                                    </div>
                                                </div>

                                            @endif
                                        </td>
                                    </tr>
                                    @empty
                                    <tr>
                                        <td colspan="5">No export request data.</td>
                                    </tr>
                                @endforelse
                                </tbody>
                            </table>
                        </div>

                    </div>

                    <div class="card-footer">
                        {{$export_requests->links()}}
                    </div>

                </div>
            </div>
        </div>
    </div>
@endsection